radioStateToString(RIL_RadioState s) {
 switch(s) {
 case RADIO_STATE_OFF: return "RADIO_OFF";
 case RADIO_STATE_UNAVAILABLE: return "RADIO_UNAVAILABLE";
 case RADIO_STATE_SIM_NOT_READY: return "RADIO_SIM_NOT_READY";
 case RADIO_STATE_SIM_LOCKED_OR_ABSENT: return "RADIO_SIM_LOCKED_OR_ABSENT";
 case RADIO_STATE_SIM_READY: return "RADIO_SIM_READY";
 case RADIO_STATE_RUIM_NOT_READY:return"RADIO_RUIM_NOT_READY";
 case RADIO_STATE_RUIM_READY:return"RADIO_RUIM_READY";
 case RADIO_STATE_RUIM_LOCKED_OR_ABSENT:return"RADIO_RUIM_LOCKED_OR_ABSENT";
 case RADIO_STATE_NV_NOT_READY:return"RADIO_NV_NOT_READY";
 case RADIO_STATE_NV_READY:return"RADIO_NV_READY";
 case RADIO_STATE_ON:return"RADIO_ON";
 default: return "<unknown state>";
 }
}
